#include <stdio.h>
#include <stdlib.h>
#include <netdb.h>
#include <netinet/in.h>
#include <string.h>
#include <unistd.h>
#include <errno.h>
#include <sys/types.h>
#include <sys/mman.h>
#include <time.h>
#include "proj1.h"

/* TODO: define Client member functions */
Client::Client(char* name,int portno){
    //initiallize the client
    server = gethostbyname(name);
    sockfd = socket(AF_INET, SOCK_STREAM, 0);
    if (sockfd < 0)
        perror("ERROR opening socket");
    bzero((char *) &serv_addr, sizeof(serv_addr));
    serv_addr.sin_family = AF_INET;
    bcopy((char *)server->h_addr,
          (char *)&serv_addr.sin_addr.s_addr,
          server->h_length);
    serv_addr.sin_port = htons(portno);
    if (connect(sockfd,(struct sockaddr *) &serv_addr,sizeof(serv_addr)) < 0)
        perror("ERROR connecting");
    //the below statement is to make the variable "price" could be shared 
    //among different folks in client
    price=(float*)mmap(NULL,sizeof(price),PROT_READ|PROT_WRITE,MAP_SHARED|MAP_ANONYMOUS,-1,0);
    
};
void Client::get_price(){
   //declare some variables used in this function
   int n;
   char buffer[256];
   char price_temp[10];
   sleep(1);
   bzero(buffer,256);
   //the below part is to gain the price generated by server 
   //and display it to user
   n = read(sockfd,buffer,255);
   if (n < 0){
        perror("ERROR reading from socket");}
   strncpy(price_temp,&buffer[1],4);
   price_temp[4]=0;
   *price=atof(price_temp);
   printf("%s",buffer);
   fflush(stdout);
//  bzero(buffer,256);
};
void Client::gen_buy_request(){ 
   //declare the variables used in this function
   int n,j;
   char buffer[256],result[10];
   float* buy_price=price;
   bzero(buffer,256);
   fgets(buffer,255,stdin);//this statement is used to react to the "input" of user
   sleep(1);
   if(*buy_price==0) return;
   //below part is to send the price at client's buying to server
   time_t mytime;
   mytime = time(NULL);
   bzero(buffer,256);
   j = sprintf( buffer,  "%.2f at %s", *buy_price,ctime(&mytime) );
   n = write(sockfd,buffer,32);
   if (n < 0){
        perror("ERROR writing to socket");exit(1);}
   //below part is to get the result of this buying from server
   //and display it to user
  // time_t mytime;
   //mytime = time(NULL);
   printf("from client: client buy  at $%.2f at %s",*buy_price, ctime(&mytime));

    /*bzero(buffer,256);
    j = sprintf( buffer,  "%.2f at %s", *buy_price,ctime(&mytime) );

    n = write(sockfd,buffer,32);
    if (n < 0){
        perror("ERROR writing to socket");exit(1);}*/
    bzero(buffer,256);
    n = read(sockfd,buffer,255);
    if (n < 0){
        perror("ERROR reading from socket");
      exit(1);
    }

   printf( "%s\n",buffer);
};


